# Generated using https://godot-build-options-generator.github.io

deprecated = "no"
module_arkit_enabled = "no"
module_bmp_enabled = "no"
module_bullet_enabled = "no"
module_camera_enabled = "no"
module_dds_enabled = "no"
module_gdnative_enabled = "no"
module_gdnavigation_enabled = "no"
module_gridmap_enabled = "no"
module_jpg_enabled = "no"
module_mobile_vr_enabled = "no"
module_opensimplex_enabled = "no"
module_opus_enabled = "no"
module_tga_enabled = "no"
module_visual_script_enabled = "no"
module_webm_enabled = "no"
module_webp_enabled = "no"
